import {parseCSV,norm,pick} from "./csv.js";
const ROOT="https://www.wienerlinien.at/ogd_realtime/doku/ogd";
const MONITOR="https://www.wienerlinien.at/ogd_realtime/monitor";
let cache={time:0,stations:[],platforms:[]};
async function text(url){const r=await fetch(url,{next:{revalidate:21600}});if(!r.ok)throw new Error(`Open Data ${r.status}`);return r.text();}
async function data(){if(cache.stations.length&&Date.now()-cache.time<21600000)return cache;const [a,b]=await Promise.all([text(`${ROOT}/wienerlinien-ogd-haltestellen.csv`),text(`${ROOT}/wienerlinien-ogd-steige.csv`)]);cache={time:Date.now(),stations:parseCSV(a),platforms:parseCSV(b)};return cache;}
const name=r=>pick(r,["NAME","HALTESTELLEN_NAME","BEZEICHNUNG"]),sid=r=>pick(r,["HALTESTELLEN_ID","ID"]),diva=r=>pick(r,["DIVA"]),fk=r=>pick(r,["FK_HALTESTELLEN_ID","HALTESTELLEN_ID"]),rbl=r=>pick(r,["RBL_NUMMER","RBL"]);
function score(q,c){q=norm(q);c=norm(c);if(q===c)return 100;if(c.includes(q)||q.includes(c))return 80;const w=q.split(" ");return 60*w.filter(x=>c.includes(x)).length/w.length;}
export async function resolve(station,line){const d=await data();const matches=d.stations.map(row=>({row,n:name(row),s:score(station,name(row))})).filter(x=>x.s>=60).sort((a,b)=>b.s-a.s).slice(0,10);const ids=[];for(const m of matches){for(const p of d.platforms){if((sid(m.row)&&fk(p)===sid(m.row))||(diva(m.row)&&diva(p)===diva(m.row))){const id=rbl(p);if(/^\d+$/.test(id))ids.push(id);}}}const candidates=[...new Set(ids)];const verified=[];for(let i=0;i<candidates.length;i+=20){const batch=candidates.slice(i,i+20);const q=batch.map(x=>`stopId=${encodeURIComponent(x)}`).join("&");const r=await fetch(`${MONITOR}?${q}`,{cache:"no-store"});if(!r.ok)continue;const j=await r.json();for(const m of j?.data?.monitors??[]){for(const l of m.lines??[]){if(norm(l.name)!==norm(line))continue;const attrs=m?.locationStop?.properties?.attributes??{};verified.push({stopId:String(attrs.rbl??attrs.rblNumber??""),station:m?.locationStop?.properties?.title??station,line:l.name,direction:l.towards??"",departures:l.departures?.departure??[]});}}}
return {station,line,candidates,verified,stopIds:[...new Set(verified.map(x=>x.stopId).filter(Boolean))]};}
export async function live(station,line){const found=await resolve(station,line);return {...found,departures:found.verified.flatMap(v=>v.departures.map(d=>({stopId:v.stopId,direction:v.direction,countdown:d.departureTime?.countdown,planned:d.departureTime?.timePlanned,real:d.departureTime?.timeReal,platform:d.vehicle?.platform}))).sort((a,b)=>(a.countdown??999)-(b.countdown??999)).slice(0,6)};}
